# Generated by Django 4.1 on 2022-09-05 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_rename_profile_profilename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileName',
            new_name='Profile',
        ),
    ]
